/*
Copyright 2014 MessageMedia
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License. 
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MessageMediaServiceBinding", Namespace="http://xml.m4u.com.au/2009")]
public partial class MessageMediaSoapService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback sendMessagesOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkRepliesOperationCompleted;
    
    private System.Threading.SendOrPostCallback checkReportsOperationCompleted;
    
    private System.Threading.SendOrPostCallback confirmRepliesOperationCompleted;
    
    private System.Threading.SendOrPostCallback confirmReportsOperationCompleted;
    
    private System.Threading.SendOrPostCallback deleteScheduledMessagesOperationCompleted;
    
    private System.Threading.SendOrPostCallback blockNumbersOperationCompleted;
    
    private System.Threading.SendOrPostCallback unblockNumbersOperationCompleted;
    
    private System.Threading.SendOrPostCallback getBlockedNumbersOperationCompleted;
    
    /// <remarks/>
    public MessageMediaSoapService() {
        this.Url = "https://soap.m4u.com.au";
    }
    
    /// <remarks/>
    public event sendMessagesCompletedEventHandler sendMessagesCompleted;
    
    /// <remarks/>
    public event checkUserCompletedEventHandler checkUserCompleted;
    
    /// <remarks/>
    public event checkRepliesCompletedEventHandler checkRepliesCompleted;
    
    /// <remarks/>
    public event checkReportsCompletedEventHandler checkReportsCompleted;
    
    /// <remarks/>
    public event confirmRepliesCompletedEventHandler confirmRepliesCompleted;
    
    /// <remarks/>
    public event confirmReportsCompletedEventHandler confirmReportsCompleted;
    
    /// <remarks/>
    public event deleteScheduledMessagesCompletedEventHandler deleteScheduledMessagesCompleted;
    
    /// <remarks/>
    public event blockNumbersCompletedEventHandler blockNumbersCompleted;
    
    /// <remarks/>
    public event unblockNumbersCompletedEventHandler unblockNumbersCompleted;
    
    /// <remarks/>
    public event getBlockedNumbersCompletedEventHandler getBlockedNumbersCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/sendMessages", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public SendMessagesResultType sendMessages(AuthenticationType authentication, SendMessagesBodyType requestBody) {
        object[] results = this.Invoke("sendMessages", new object[] {
                    authentication,
                    requestBody});
        return ((SendMessagesResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsendMessages(AuthenticationType authentication, SendMessagesBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sendMessages", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public SendMessagesResultType EndsendMessages(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((SendMessagesResultType)(results[0]));
    }
    
    /// <remarks/>
    public void sendMessagesAsync(AuthenticationType authentication, SendMessagesBodyType requestBody) {
        this.sendMessagesAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void sendMessagesAsync(AuthenticationType authentication, SendMessagesBodyType requestBody, object userState) {
        if ((this.sendMessagesOperationCompleted == null)) {
            this.sendMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendMessagesOperationCompleted);
        }
        this.InvokeAsync("sendMessages", new object[] {
                    authentication,
                    requestBody}, this.sendMessagesOperationCompleted, userState);
    }
    
    private void OnsendMessagesOperationCompleted(object arg) {
        if ((this.sendMessagesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendMessagesCompleted(this, new sendMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/checkUser", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public CheckUserResultType checkUser(AuthenticationType authentication) {
        object[] results = this.Invoke("checkUser", new object[] {
                    authentication});
        return ((CheckUserResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckUser(AuthenticationType authentication, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkUser", new object[] {
                    authentication}, callback, asyncState);
    }
    
    /// <remarks/>
    public CheckUserResultType EndcheckUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CheckUserResultType)(results[0]));
    }
    
    /// <remarks/>
    public void checkUserAsync(AuthenticationType authentication) {
        this.checkUserAsync(authentication, null);
    }
    
    /// <remarks/>
    public void checkUserAsync(AuthenticationType authentication, object userState) {
        if ((this.checkUserOperationCompleted == null)) {
            this.checkUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckUserOperationCompleted);
        }
        this.InvokeAsync("checkUser", new object[] {
                    authentication}, this.checkUserOperationCompleted, userState);
    }
    
    private void OncheckUserOperationCompleted(object arg) {
        if ((this.checkUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkUserCompleted(this, new checkUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/checkReplies", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public CheckRepliesResultType checkReplies(AuthenticationType authentication, CheckRepliesBodyType requestBody) {
        object[] results = this.Invoke("checkReplies", new object[] {
                    authentication,
                    requestBody});
        return ((CheckRepliesResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckReplies(AuthenticationType authentication, CheckRepliesBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkReplies", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public CheckRepliesResultType EndcheckReplies(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CheckRepliesResultType)(results[0]));
    }
    
    /// <remarks/>
    public void checkRepliesAsync(AuthenticationType authentication, CheckRepliesBodyType requestBody) {
        this.checkRepliesAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void checkRepliesAsync(AuthenticationType authentication, CheckRepliesBodyType requestBody, object userState) {
        if ((this.checkRepliesOperationCompleted == null)) {
            this.checkRepliesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckRepliesOperationCompleted);
        }
        this.InvokeAsync("checkReplies", new object[] {
                    authentication,
                    requestBody}, this.checkRepliesOperationCompleted, userState);
    }
    
    private void OncheckRepliesOperationCompleted(object arg) {
        if ((this.checkRepliesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkRepliesCompleted(this, new checkRepliesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/checkReports", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public CheckReportsResultType checkReports(AuthenticationType authentication, CheckReportsBodyType requestBody) {
        object[] results = this.Invoke("checkReports", new object[] {
                    authentication,
                    requestBody});
        return ((CheckReportsResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincheckReports(AuthenticationType authentication, CheckReportsBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("checkReports", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public CheckReportsResultType EndcheckReports(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CheckReportsResultType)(results[0]));
    }
    
    /// <remarks/>
    public void checkReportsAsync(AuthenticationType authentication, CheckReportsBodyType requestBody) {
        this.checkReportsAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void checkReportsAsync(AuthenticationType authentication, CheckReportsBodyType requestBody, object userState) {
        if ((this.checkReportsOperationCompleted == null)) {
            this.checkReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckReportsOperationCompleted);
        }
        this.InvokeAsync("checkReports", new object[] {
                    authentication,
                    requestBody}, this.checkReportsOperationCompleted, userState);
    }
    
    private void OncheckReportsOperationCompleted(object arg) {
        if ((this.checkReportsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.checkReportsCompleted(this, new checkReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/confirmReplies", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public ConfirmRepliesResultType confirmReplies(AuthenticationType authentication, ConfirmRepliesBodyType requestBody) {
        object[] results = this.Invoke("confirmReplies", new object[] {
                    authentication,
                    requestBody});
        return ((ConfirmRepliesResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconfirmReplies(AuthenticationType authentication, ConfirmRepliesBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("confirmReplies", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public ConfirmRepliesResultType EndconfirmReplies(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ConfirmRepliesResultType)(results[0]));
    }
    
    /// <remarks/>
    public void confirmRepliesAsync(AuthenticationType authentication, ConfirmRepliesBodyType requestBody) {
        this.confirmRepliesAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void confirmRepliesAsync(AuthenticationType authentication, ConfirmRepliesBodyType requestBody, object userState) {
        if ((this.confirmRepliesOperationCompleted == null)) {
            this.confirmRepliesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmRepliesOperationCompleted);
        }
        this.InvokeAsync("confirmReplies", new object[] {
                    authentication,
                    requestBody}, this.confirmRepliesOperationCompleted, userState);
    }
    
    private void OnconfirmRepliesOperationCompleted(object arg) {
        if ((this.confirmRepliesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.confirmRepliesCompleted(this, new confirmRepliesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/confirmReports", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public ConfirmReportsResultType confirmReports(AuthenticationType authentication, ConfirmReportsBodyType requestBody) {
        object[] results = this.Invoke("confirmReports", new object[] {
                    authentication,
                    requestBody});
        return ((ConfirmReportsResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconfirmReports(AuthenticationType authentication, ConfirmReportsBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("confirmReports", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public ConfirmReportsResultType EndconfirmReports(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ConfirmReportsResultType)(results[0]));
    }
    
    /// <remarks/>
    public void confirmReportsAsync(AuthenticationType authentication, ConfirmReportsBodyType requestBody) {
        this.confirmReportsAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void confirmReportsAsync(AuthenticationType authentication, ConfirmReportsBodyType requestBody, object userState) {
        if ((this.confirmReportsOperationCompleted == null)) {
            this.confirmReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmReportsOperationCompleted);
        }
        this.InvokeAsync("confirmReports", new object[] {
                    authentication,
                    requestBody}, this.confirmReportsOperationCompleted, userState);
    }
    
    private void OnconfirmReportsOperationCompleted(object arg) {
        if ((this.confirmReportsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.confirmReportsCompleted(this, new confirmReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/soap/deleteScheduledMessages", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public DeleteScheduledMessagesResultType deleteScheduledMessages(AuthenticationType authentication, DeleteScheduledMessagesBodyType requestBody) {
        object[] results = this.Invoke("deleteScheduledMessages", new object[] {
                    authentication,
                    requestBody});
        return ((DeleteScheduledMessagesResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindeleteScheduledMessages(AuthenticationType authentication, DeleteScheduledMessagesBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("deleteScheduledMessages", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public DeleteScheduledMessagesResultType EnddeleteScheduledMessages(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((DeleteScheduledMessagesResultType)(results[0]));
    }
    
    /// <remarks/>
    public void deleteScheduledMessagesAsync(AuthenticationType authentication, DeleteScheduledMessagesBodyType requestBody) {
        this.deleteScheduledMessagesAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void deleteScheduledMessagesAsync(AuthenticationType authentication, DeleteScheduledMessagesBodyType requestBody, object userState) {
        if ((this.deleteScheduledMessagesOperationCompleted == null)) {
            this.deleteScheduledMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteScheduledMessagesOperationCompleted);
        }
        this.InvokeAsync("deleteScheduledMessages", new object[] {
                    authentication,
                    requestBody}, this.deleteScheduledMessagesOperationCompleted, userState);
    }
    
    private void OndeleteScheduledMessagesOperationCompleted(object arg) {
        if ((this.deleteScheduledMessagesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.deleteScheduledMessagesCompleted(this, new deleteScheduledMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/blockNumbers", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public BlockNumbersResultType blockNumbers(AuthenticationType authentication, BlockNumbersBodyType requestBody) {
        object[] results = this.Invoke("blockNumbers", new object[] {
                    authentication,
                    requestBody});
        return ((BlockNumbersResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginblockNumbers(AuthenticationType authentication, BlockNumbersBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("blockNumbers", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public BlockNumbersResultType EndblockNumbers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BlockNumbersResultType)(results[0]));
    }
    
    /// <remarks/>
    public void blockNumbersAsync(AuthenticationType authentication, BlockNumbersBodyType requestBody) {
        this.blockNumbersAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void blockNumbersAsync(AuthenticationType authentication, BlockNumbersBodyType requestBody, object userState) {
        if ((this.blockNumbersOperationCompleted == null)) {
            this.blockNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnblockNumbersOperationCompleted);
        }
        this.InvokeAsync("blockNumbers", new object[] {
                    authentication,
                    requestBody}, this.blockNumbersOperationCompleted, userState);
    }
    
    private void OnblockNumbersOperationCompleted(object arg) {
        if ((this.blockNumbersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.blockNumbersCompleted(this, new blockNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/unblockNumbers", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public UnblockNumbersResultType unblockNumbers(AuthenticationType authentication, UnblockNumbersBodyType requestBody) {
        object[] results = this.Invoke("unblockNumbers", new object[] {
                    authentication,
                    requestBody});
        return ((UnblockNumbersResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginunblockNumbers(AuthenticationType authentication, UnblockNumbersBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("unblockNumbers", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public UnblockNumbersResultType EndunblockNumbers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((UnblockNumbersResultType)(results[0]));
    }
    
    /// <remarks/>
    public void unblockNumbersAsync(AuthenticationType authentication, UnblockNumbersBodyType requestBody) {
        this.unblockNumbersAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void unblockNumbersAsync(AuthenticationType authentication, UnblockNumbersBodyType requestBody, object userState) {
        if ((this.unblockNumbersOperationCompleted == null)) {
            this.unblockNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunblockNumbersOperationCompleted);
        }
        this.InvokeAsync("unblockNumbers", new object[] {
                    authentication,
                    requestBody}, this.unblockNumbersOperationCompleted, userState);
    }
    
    private void OnunblockNumbersOperationCompleted(object arg) {
        if ((this.unblockNumbersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.unblockNumbersCompleted(this, new unblockNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xml.m4u.com.au/2009/getBlockedNumbers", RequestNamespace="http://xml.m4u.com.au/2009", ResponseNamespace="http://xml.m4u.com.au/2009", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("result")]
    public GetBlockedNumbersResultType getBlockedNumbers(AuthenticationType authentication, GetBlockedNumbersBodyType requestBody) {
        object[] results = this.Invoke("getBlockedNumbers", new object[] {
                    authentication,
                    requestBody});
        return ((GetBlockedNumbersResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetBlockedNumbers(AuthenticationType authentication, GetBlockedNumbersBodyType requestBody, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getBlockedNumbers", new object[] {
                    authentication,
                    requestBody}, callback, asyncState);
    }
    
    /// <remarks/>
    public GetBlockedNumbersResultType EndgetBlockedNumbers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((GetBlockedNumbersResultType)(results[0]));
    }
    
    /// <remarks/>
    public void getBlockedNumbersAsync(AuthenticationType authentication, GetBlockedNumbersBodyType requestBody) {
        this.getBlockedNumbersAsync(authentication, requestBody, null);
    }
    
    /// <remarks/>
    public void getBlockedNumbersAsync(AuthenticationType authentication, GetBlockedNumbersBodyType requestBody, object userState) {
        if ((this.getBlockedNumbersOperationCompleted == null)) {
            this.getBlockedNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBlockedNumbersOperationCompleted);
        }
        this.InvokeAsync("getBlockedNumbers", new object[] {
                    authentication,
                    requestBody}, this.getBlockedNumbersOperationCompleted, userState);
    }
    
    private void OngetBlockedNumbersOperationCompleted(object arg) {
        if ((this.getBlockedNumbersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getBlockedNumbersCompleted(this, new getBlockedNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class AuthenticationType {
    
    private string userIdField;
    
    private string passwordField;
    
    /// <remarks/>
    public string userId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class GetBlockedNumbersResultType {
    
    private RecipientType[] recipientsField;
    
    private uint foundField;
    
    private uint returnedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("recipient", IsNullable=false)]
    public RecipientType[] recipients {
        get {
            return this.recipientsField;
        }
        set {
            this.recipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint found {
        get {
            return this.foundField;
        }
        set {
            this.foundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint returned {
        get {
            return this.returnedField;
        }
        set {
            this.returnedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class RecipientType {
    
    private uint uidField;
    
    private string valueField;
    
    public RecipientType() {
        this.uidField = ((uint)(0));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class GetBlockedNumbersBodyType {
    
    private uint maximumRecipientsField;
    
    private bool maximumRecipientsFieldSpecified;
    
    /// <remarks/>
    public uint maximumRecipients {
        get {
            return this.maximumRecipientsField;
        }
        set {
            this.maximumRecipientsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumRecipientsSpecified {
        get {
            return this.maximumRecipientsFieldSpecified;
        }
        set {
            this.maximumRecipientsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class UnblockNumbersResultType {
    
    private MessageErrorType[] errorsField;
    
    private uint unblockedField;
    
    private uint failedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
    public MessageErrorType[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint unblocked {
        get {
            return this.unblockedField;
        }
        set {
            this.unblockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class MessageErrorType {
    
    private RecipientType[] recipientsField;
    
    private string contentField;
    
    private MessageErrorCodeType codeField;
    
    private uint sequenceNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("recipient", IsNullable=false)]
    public RecipientType[] recipients {
        get {
            return this.recipientsField;
        }
        set {
            this.recipientsField = value;
        }
    }
    
    /// <remarks/>
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MessageErrorCodeType code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint sequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public enum MessageErrorCodeType {
    
    /// <remarks/>
    invalidRecipient,
    
    /// <remarks/>
    recipientBlocked,
    
    /// <remarks/>
    emptyMessageContent,
    
    /// <remarks/>
    messageLengthLimit,
    
    /// <remarks/>
    other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class UnblockNumbersBodyType {
    
    private RecipientType[] recipientsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("recipient", IsNullable=false)]
    public RecipientType[] recipients {
        get {
            return this.recipientsField;
        }
        set {
            this.recipientsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class BlockNumbersResultType {
    
    private MessageErrorType[] errorsField;
    
    private uint blockedField;
    
    private uint failedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
    public MessageErrorType[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint blocked {
        get {
            return this.blockedField;
        }
        set {
            this.blockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class BlockNumbersBodyType {
    
    private RecipientType[] recipientsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("recipient", IsNullable=false)]
    public RecipientType[] recipients {
        get {
            return this.recipientsField;
        }
        set {
            this.recipientsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class DeleteScheduledMessagesResultType {
    
    private uint unscheduledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint unscheduled {
        get {
            return this.unscheduledField;
        }
        set {
            this.unscheduledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class MessageIdType {
    
    private uint messageIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint messageId {
        get {
            return this.messageIdField;
        }
        set {
            this.messageIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class DeleteScheduledMessagesBodyType {
    
    private MessageIdType[] messagesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("message", IsNullable=false)]
    public MessageIdType[] messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class ConfirmReportsResultType {
    
    private uint confirmedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint confirmed {
        get {
            return this.confirmedField;
        }
        set {
            this.confirmedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class ConfirmReportsBodyType {
    
    private ConfirmItemType[] reportsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable=false)]
    public ConfirmItemType[] reports {
        get {
            return this.reportsField;
        }
        set {
            this.reportsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class ConfirmItemType {
    
    private uint receiptIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint receiptId {
        get {
            return this.receiptIdField;
        }
        set {
            this.receiptIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class ConfirmRepliesResultType {
    
    private uint confirmedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint confirmed {
        get {
            return this.confirmedField;
        }
        set {
            this.confirmedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class ConfirmRepliesBodyType {
    
    private ConfirmItemType[] repliesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("reply", IsNullable=false)]
    public ConfirmItemType[] replies {
        get {
            return this.repliesField;
        }
        set {
            this.repliesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class ReportType {
    
    private string recipientField;
    
    private System.DateTime timestampField;
    
    private uint uidField;
    
    private uint receiptIdField;
    
    private DeliveryStatusType statusField;
    
    /// <remarks/>
    public string recipient {
        get {
            return this.recipientField;
        }
        set {
            this.recipientField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint receiptId {
        get {
            return this.receiptIdField;
        }
        set {
            this.receiptIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DeliveryStatusType status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public enum DeliveryStatusType {
    
    /// <remarks/>
    delivered,
    
    /// <remarks/>
    pending,
    
    /// <remarks/>
    failed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class CheckReportsResultType {
    
    private ReportType[] reportsField;
    
    private uint returnedField;
    
    private uint remainingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable=false)]
    public ReportType[] reports {
        get {
            return this.reportsField;
        }
        set {
            this.reportsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint returned {
        get {
            return this.returnedField;
        }
        set {
            this.returnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint remaining {
        get {
            return this.remainingField;
        }
        set {
            this.remainingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class CheckReportsBodyType {
    
    private uint maximumReportsField;
    
    private bool maximumReportsFieldSpecified;
    
    /// <remarks/>
    public uint maximumReports {
        get {
            return this.maximumReportsField;
        }
        set {
            this.maximumReportsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumReportsSpecified {
        get {
            return this.maximumReportsFieldSpecified;
        }
        set {
            this.maximumReportsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class ReplyType {
    
    private string originField;
    
    private System.DateTime receivedField;
    
    private string contentField;
    
    private MessageFormatType formatField;
    
    private uint uidField;
    
    private uint receiptIdField;
    
    /// <remarks/>
    public string origin {
        get {
            return this.originField;
        }
        set {
            this.originField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime received {
        get {
            return this.receivedField;
        }
        set {
            this.receivedField = value;
        }
    }
    
    /// <remarks/>
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MessageFormatType format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint uid {
        get {
            return this.uidField;
        }
        set {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint receiptId {
        get {
            return this.receiptIdField;
        }
        set {
            this.receiptIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public enum MessageFormatType {
    
    /// <remarks/>
    SMS,
    
    /// <remarks/>
    voice,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class CheckRepliesResultType {
    
    private ReplyType[] repliesField;
    
    private uint returnedField;
    
    private uint remainingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("reply", IsNullable=false)]
    public ReplyType[] replies {
        get {
            return this.repliesField;
        }
        set {
            this.repliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint returned {
        get {
            return this.returnedField;
        }
        set {
            this.returnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint remaining {
        get {
            return this.remainingField;
        }
        set {
            this.remainingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class CheckRepliesBodyType {
    
    private uint maximumRepliesField;
    
    private bool maximumRepliesFieldSpecified;
    
    /// <remarks/>
    public uint maximumReplies {
        get {
            return this.maximumRepliesField;
        }
        set {
            this.maximumRepliesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maximumRepliesSpecified {
        get {
            return this.maximumRepliesFieldSpecified;
        }
        set {
            this.maximumRepliesFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class CheckUserResultType {
    
    private AccountDetailsType accountDetailsField;
    
    /// <remarks/>
    public AccountDetailsType accountDetails {
        get {
            return this.accountDetailsField;
        }
        set {
            this.accountDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class AccountDetailsType {
    
    private string typeField;
    
    private uint creditLimitField;
    
    private uint creditRemainingField;
    
    public AccountDetailsType() {
        this.typeField = "daily";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint creditLimit {
        get {
            return this.creditLimitField;
        }
        set {
            this.creditLimitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint creditRemaining {
        get {
            return this.creditRemainingField;
        }
        set {
            this.creditRemainingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class SendMessagesResultType {
    
    private AccountDetailsType accountDetailsField;
    
    private MessageErrorType[] errorsField;
    
    private uint sentField;
    
    private uint scheduledField;
    
    private uint failedField;
    
    /// <summary>
    /// Use of these properties on the SendMessagesResultType is deprecated. Use the CheckUserResultType instead.  This will support migration to the REST client.
    /// </summary>
    public AccountDetailsType accountDetails {
        get {
            return this.accountDetailsField;
        }
        set {
            this.accountDetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
    public MessageErrorType[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint sent {
        get {
            return this.sentField;
        }
        set {
            this.sentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint scheduled {
        get {
            return this.scheduledField;
        }
        set {
            this.scheduledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class MessageTagType {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class MessageType {
    
    private string originField;
    
    private RecipientType[] recipientsField;
    
    private string contentField;
    
    private System.DateTime scheduledField;
    
    private bool scheduledFieldSpecified;
    
    private bool deliveryReportField;
    
    private byte validityPeriodField;
    
    private MessageTagType[] tagsField;
    
    private MessageFormatType formatField;
    
    private uint sequenceNumberField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    public MessageType() {
        this.deliveryReportField = false;
        this.validityPeriodField = ((byte)(169));
        this.formatField = MessageFormatType.SMS;
        this.sequenceNumberField = ((uint)(0));
    }
    
    /// <remarks/>
    public string origin {
        get {
            return this.originField;
        }
        set {
            this.originField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("recipient", IsNullable=false)]
    public RecipientType[] recipients {
        get {
            return this.recipientsField;
        }
        set {
            this.recipientsField = value;
        }
    }
    
    /// <remarks/>
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime scheduled {
        get {
            return this.scheduledField;
        }
        set {
            this.scheduledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool scheduledSpecified {
        get {
            return this.scheduledFieldSpecified;
        }
        set {
            this.scheduledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool deliveryReport {
        get {
            return this.deliveryReportField;
        }
        set {
            this.deliveryReportField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "169")]
    public byte validityPeriod {
        get {
            return this.validityPeriodField;
        }
        set {
            this.validityPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("tag", IsNullable=false)]
    public MessageTagType[] tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(MessageFormatType.SMS)]
    public MessageFormatType format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <summary>
    /// (Optional) This attribute specifies a sequence number that is assigned to the message and is used to identify the message if an error occurs. Each message error in the response will specify the sequence number of the message that caused the error. Sequence numbers should be unique within the request. 1 to 2147483647.
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint sequenceNumber {
        get {
            return this.sequenceNumberField;
        }
        set {
            this.sequenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class MessageListType {
    
    private MessageType[] messageField;
    
    private MessageSendModeType sendModeField;
    
    public MessageListType() {
        this.sendModeField = MessageSendModeType.normal;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("message")]
    public MessageType[] message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(MessageSendModeType.normal)]
    public MessageSendModeType sendMode {
        get {
            return this.sendModeField;
        }
        set {
            this.sendModeField = value;
        }
    }
}

/// <summary>
/// "dropAll" – to drop (not send) the requested messages, and return a result indicating that messages were sent / scheduled successfully or failed to send at random.
/// "dropAllWithErrors" – to drop (not send) the requested messages, and return a result indicating that all messages failed to send.
/// "dropAllWithSuccess" – to drop (not send) the requested messages, but return a result indicating all messages were sent / scheduled successfully.
/// "normal" – to send the requested messages as normal.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public enum MessageSendModeType {
    
    /// <remarks/>
    dropAll,
    
    /// <remarks/>
    dropAllWithErrors,
    
    /// <remarks/>
    dropAllWithSuccess,
    
    /// <remarks/>
    normal,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.m4u.com.au/2009")]
public partial class SendMessagesBodyType {
    
    private MessageListType messagesField;
    
    /// <remarks/>
    public MessageListType messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void sendMessagesCompletedEventHandler(object sender, sendMessagesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sendMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sendMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public SendMessagesResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((SendMessagesResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void checkUserCompletedEventHandler(object sender, checkUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CheckUserResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CheckUserResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void checkRepliesCompletedEventHandler(object sender, checkRepliesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkRepliesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkRepliesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CheckRepliesResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CheckRepliesResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void checkReportsCompletedEventHandler(object sender, checkReportsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal checkReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CheckReportsResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CheckReportsResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void confirmRepliesCompletedEventHandler(object sender, confirmRepliesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class confirmRepliesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal confirmRepliesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ConfirmRepliesResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ConfirmRepliesResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void confirmReportsCompletedEventHandler(object sender, confirmReportsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class confirmReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal confirmReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ConfirmReportsResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ConfirmReportsResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void deleteScheduledMessagesCompletedEventHandler(object sender, deleteScheduledMessagesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class deleteScheduledMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal deleteScheduledMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public DeleteScheduledMessagesResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((DeleteScheduledMessagesResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void blockNumbersCompletedEventHandler(object sender, blockNumbersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class blockNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal blockNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BlockNumbersResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BlockNumbersResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void unblockNumbersCompletedEventHandler(object sender, unblockNumbersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class unblockNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal unblockNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public UnblockNumbersResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((UnblockNumbersResultType)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
public delegate void getBlockedNumbersCompletedEventHandler(object sender, getBlockedNumbersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.18020")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getBlockedNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getBlockedNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public GetBlockedNumbersResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((GetBlockedNumbersResultType)(this.results[0]));
        }
    }
}
